branches:
    except:
        - gh-pages

skip_tags: true

environment:
    global:
        # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
        # /E:ON and /V:ON options are not enabled in the batch script intepreter
        # See: http://stackoverflow.com/a/13751649/163740
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tests\\appveyor\\run_with_env.cmd"

    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7.x"
          PYTHON_VER_SHORT: "27"
          PYTHON_ARCH: "32"
          PYWIN32_URL: "https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win32-py2.7.exe"

        - PYTHON: "C:\\Python27-x64"
          PYTHON_VERSION: "2.7.x"
          PYTHON_VER_SHORT: "27"
          PYTHON_ARCH: "64"
          PYWIN32_URL: "https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win-amd64-py2.7.exe"

install:
    # Install utils for building exe
    - choco install -y curl 7zip InnoSetup
    - set PATH="C:\Program Files\7-Zip";"C:\Program Files (x86)\Inno Setup 5";%PATH%

    # Install CouchDB
    - appveyor DownloadFile https://dl.bintray.com/apache/couchdb/win/1.6.1/setup-couchdb-1.6.1_R16B02.exe -FileName c:\couchdb.exe
    - "c:\\couchdb.exe /SILENT /NORESTART /SP-"

    # Install Python (from the official .msi of http://python.org) and pip when
    # not already installed.
    - ps: if (-not(Test-Path($env:PYTHON))) { & tests\appveyor\install.ps1 }

    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Check that we have the expected version and architecture for Python
    - python -c "import sys;print(sys.version)"

    # Upgrade pip and setuptools
    - pip install --disable-pip-version-check --user --upgrade pip setuptools

    # Install test requirements
    - pip install coveralls unittest2 nose nose-testconfig mock wheel

    # Install requirements manually
    # py2exe need all depends unzipped
    # see: http://www.py2exe.org/index.cgi/ExeWithEggs
    - python -m easy_install -Z restkit==4.2.2 watchdog==0.6.0

    # Install py2exe
    - pip install http://sourceforge.net/projects/py2exe/files/latest/download?source=files
    - ps: (new-object net.webclient).DownloadFile($env:PYWIN32_URL, 'c:\\pywin32.exe')
    - "%PYTHON%/Scripts/easy_install.exe c:\\pywin32.exe"

    # Get app_path.exe
    - curl -LO http://www.barisione.org/files/add_path.zip
    - 7z x add_path.zip

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
    - python setup.py install

    # Build wheel
    - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"

    # Build standalone binary via py2exe
    - "%WITH_COMPILER% %PYTHON%/python setup.py build"
    - python -m py2exe.mf -d resources\scripts\couchapp
    - python setup.py py2exe

    # Add path for couchapp.exe
    - ls dist\
    - "SET PATH=%CD%\\dist;%PATH%"

    # prepare templates dir for testing
    - ps: cp -R dist\couchapp\templates dist\templates

    # tests for standalone binary
    - "nosetests --tests=tests\\test_cli.py"

after_test:
    # Pack ``dist`` via Inno Setup
    - copy add_path.exe dist\
    - ps: ($Env:COUCHAPP_VER = python -c 'import couchapp; print(couchapp.__version__)')
    - ps: ($Env:COMMIT = $Env:APPVEYOR_REPO_COMMIT.Substring(0, 7))
    - iscc resources\win32\couchapp.iss

artifacts:
    - path: Output\*
    - path: dist\*.whl
